version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - build
      - test

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install-npm
          command: 'npm install'
  test: 
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: jest-test
          command: 'npm run test'